<#
.SYNOPSIS
    Automated Windows Environment Setup for WSL (Alacritty + PowerToys + JetBrainsMono Nerd Font)
.DESCRIPTION
    Installs Alacritty terminal emulator, Microsoft PowerToys, and JetBrainsMono Nerd Font via WinGet.
    Automatically configures:
    - Alacritty with Tokyo Night theme & direct WSL shell integration.
    - PowerToys Run with Win + Space (Spotlight-like launcher).
    - PowerToys Keyboard Manager with Win + W -> Alt + F4 (Close application, Omakub style).
    - WSL 2 performance & memory cap via .wslconfig.
.NOTES
    Run from PowerShell (no administrator privileges strictly required unless WinGet prompts).
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  🚀 Windows Setup: Alacritty + PowerToys + WSL Tools       " -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# 1. Check WinGet availability
Write-Host "[1/6] Checking WinGet package manager..." -ForegroundColor Yellow
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Error "WinGet is not available on this system. Please install 'App Installer' from the Microsoft Store or update Windows 10/11."
    exit 1
}
Write-Host "  ✓ WinGet is available." -ForegroundColor Green

# Helper function to install package via winget idempotently
function Install-WingetApp {
    param(
        [Parameter(Mandatory=$true)][string]$PackageId,
        [Parameter(Mandatory=$true)][string]$DisplayName,
        [string]$FallbackId = ""
    )

    Write-Host "  Checking $DisplayName ($PackageId)..." -NoNewline
    $listOutput = winget list --id $PackageId --exact 2>&1 | Out-String

    if ($listOutput -match [regex]::Escape($PackageId)) {
        Write-Host " [Already Installed]" -ForegroundColor Green
        return
    }

    if ($FallbackId) {
        $fallbackOutput = winget list --id $FallbackId --exact 2>&1 | Out-String
        if ($fallbackOutput -match [regex]::Escape($FallbackId)) {
            Write-Host " [Already Installed ($FallbackId)]" -ForegroundColor Green
            return
        }
    }

    Write-Host " [Installing...]" -ForegroundColor Yellow
    $installArgs = @("install", "--id", $PackageId, "--exact", "--silent", "--accept-package-agreements", "--accept-source-agreements")
    $process = Start-Process -FilePath "winget" -ArgumentList $installArgs -Wait -PassThru -NoNewWindow

    if ($process.ExitCode -ne 0 -and $FallbackId) {
        Write-Host "  Trying fallback ID: $FallbackId..." -ForegroundColor Yellow
        $fallbackArgs = @("install", "--id", $FallbackId, "--exact", "--silent", "--accept-package-agreements", "--accept-source-agreements")
        $process = Start-Process -FilePath "winget" -ArgumentList $fallbackArgs -Wait -PassThru -NoNewWindow
    }

    if ($process.ExitCode -eq 0) {
        Write-Host "  ✓ Successfully installed $DisplayName" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️ WinGet returned exit code $($process.ExitCode) for $DisplayName (it may require manual review or a restart)." -ForegroundColor DarkYellow
    }
}

# 2. Install Alacritty
Write-Host ""
Write-Host "[2/6] Installing Alacritty GPU-accelerated Terminal..." -ForegroundColor Yellow
Install-WingetApp -PackageId "Alacritty.Alacritty" -DisplayName "Alacritty"

# 3. Install JetBrainsMono Nerd Font
Write-Host ""
Write-Host "[3/6] Installing JetBrainsMono Nerd Font..." -ForegroundColor Yellow
Install-WingetApp -PackageId "DEVCOM.JetBrainsMonoNerdFont" -DisplayName "JetBrainsMono Nerd Font" -FallbackId "JetBrains.JetBrainsMono.NerdFont"

# 4. Install Microsoft PowerToys
Write-Host ""
Write-Host "[4/6] Installing Microsoft PowerToys..." -ForegroundColor Yellow
Install-WingetApp -PackageId "Microsoft.PowerToys" -DisplayName "Microsoft PowerToys"

# 5. Configure Alacritty
Write-Host ""
Write-Host "[5/6] Configuring Alacritty for WSL & Tokyo Night Theme..." -ForegroundColor Yellow

$alacrittyConfigDir = Join-Path -Path $env:APPDATA -ChildPath "alacritty"
if (-not (Test-Path -Path $alacrittyConfigDir)) {
    New-Item -ItemType Directory -Path $alacrittyConfigDir -Force | Out-Null
}

$alacrittyConfigFile = Join-Path -Path $alacrittyConfigDir -ChildPath "alacritty.toml"

# Backup existing config if present
if (Test-Path -Path $alacrittyConfigFile) {
    $backupFile = Join-Path -Path $alacrittyConfigDir -ChildPath "alacritty.toml.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $alacrittyConfigFile -Destination $backupFile -Force
    Write-Host "  ✓ Existing configuration backed up to $(Split-Path $backupFile -Leaf)" -ForegroundColor DarkGray
}

$alacrittyConfigContent = @'
# ==============================================================================
#  Alacritty Configuration — WSL Development Environment
#  Auto-generated by WSL-Environment-Setup
# ==============================================================================

[general]
import = []

[env]
TERM = "xterm-256color"

# ------------------------------------------------------------------------------
# Terminal Shell (Directly launches WSL)
# ------------------------------------------------------------------------------
[terminal.shell]
program = "wsl.exe"
args    = ["--cd", "~"]

# ------------------------------------------------------------------------------
# Window Settings
# ------------------------------------------------------------------------------
[window]
padding         = { x = 14, y = 12 }
dynamic_padding = true
decorations     = "Full"
opacity         = 0.96
blur            = true
startup_mode    = "Maximized"
title           = "WSL (Linux)"
dynamic_title   = true

# ------------------------------------------------------------------------------
# Typography & Fonts
# ------------------------------------------------------------------------------
[font]
size = 11
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

# ------------------------------------------------------------------------------
# Cursor Settings
# ------------------------------------------------------------------------------
[cursor]
style          = { shape = "Beam", blinking = "On" }
blink_interval = 600

# ------------------------------------------------------------------------------
# Scrolling
# ------------------------------------------------------------------------------
[scrolling]
history    = 10000
multiplier = 3

# ------------------------------------------------------------------------------
# Color Scheme: Tokyo Night Dark (Consistent with Neovim & Zellij)
# ------------------------------------------------------------------------------
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
text   = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
background = "#283457"
text       = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

# ------------------------------------------------------------------------------
# Keybindings (Familiar copy/paste shortcuts)
# ------------------------------------------------------------------------------
[keyboard]
bindings = [
  { key = "C",     mods = "Control|Shift", action = "Copy" },
  { key = "V",     mods = "Control|Shift", action = "Paste" },
  { key = "Plus",  mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",  mods = "Control",       action = "ResetFontSize" }
]
'@

Set-Content -Path $alacrittyConfigFile -Value $alacrittyConfigContent -Encoding UTF8
Write-Host "  ✓ Wrote configuration to $alacrittyConfigFile" -ForegroundColor Green

# 6. Configure PowerToys Keybindings (Win+Space -> Spotlight, Win+W -> Close Application)
Write-Host ""
Write-Host "[6/6] Configuring PowerToys Shortcuts (Win+Space & Win+W Omakub Style)..." -ForegroundColor Yellow

$powerToysRootDir = Join-Path -Path $env:LOCALAPPDATA -ChildPath "Microsoft\PowerToys"
$powerToysRunDir  = Join-Path -Path $powerToysRootDir -ChildPath "PowerToys Run"
$powerToysKbmDir  = Join-Path -Path $powerToysRootDir -ChildPath "Keyboard Manager"

# Stop PowerToys gracefully if running to avoid overwriting settings
Get-Process -Name "PowerToys*", "PowerToys.KeyboardManagerEngine" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

# Ensure directories exist
@($powerToysRootDir, $powerToysRunDir, $powerToysKbmDir) | ForEach-Object {
    if (-not (Test-Path -Path $_)) {
        New-Item -ItemType Directory -Path $_ -Force | Out-Null
    }
}

# 6a. Main PowerToys Settings (Enable modules & startup)
$ptSettingsFile = Join-Path -Path $powerToysRootDir -ChildPath "settings.json"
$ptSettingsObj = @{
    "startup" = $true
    "enabled" = @{
        "PowerToys Run"    = $true
        "Keyboard Manager" = $true
    }
}

if (Test-Path -Path $ptSettingsFile) {
    try {
        $existingPtSettings = Get-Content -Path $ptSettingsFile -Raw | ConvertFrom-Json
        if ($null -eq $existingPtSettings.enabled) {
            $existingPtSettings | Add-Member -MemberType NoteProperty -Name "enabled" -Value ([PSCustomObject]@{})
        }
        $existingPtSettings.startup = $true
        $existingPtSettings.enabled.'PowerToys Run' = $true
        $existingPtSettings.enabled.'Keyboard Manager' = $true
        $ptSettingsJson = $existingPtSettings | ConvertTo-Json -Depth 10
    } catch {
        $ptSettingsJson = $ptSettingsObj | ConvertTo-Json -Depth 10
    }
} else {
    $ptSettingsJson = $ptSettingsObj | ConvertTo-Json -Depth 10
}
Set-Content -Path $ptSettingsFile -Value $ptSettingsJson -Encoding UTF8
Write-Host "  ✓ Enabled PowerToys Run & Keyboard Manager in $ptSettingsFile" -ForegroundColor Green

# 6b. PowerToys Run (Set shortcut to Win + Space, VK_SPACE 32)
$ptRunSettingsFile = Join-Path -Path $powerToysRunDir -ChildPath "settings.json"
$ptRunSettingsContent = @'
{
  "name": "PowerToys Run",
  "version": "1.0",
  "properties": {
    "open_powerlauncher": {
      "win": true,
      "ctrl": false,
      "alt": false,
      "shift": false,
      "code": 32,
      "key": "Space"
    }
  }
}
'@
Set-Content -Path $ptRunSettingsFile -Value $ptRunSettingsContent -Encoding UTF8
Write-Host "  ✓ Configured PowerToys Run shortcut: Win + Space (Spotlight style)" -ForegroundColor Green

# 6c. Keyboard Manager (Remap Win + W [91;87] -> Alt + F4 [164;115] to close active application)
$ptKbmDefaultFile = Join-Path -Path $powerToysKbmDir -ChildPath "default.json"
$ptKbmDefaultContent = @'
{
  "remapKeys": {
    "inProcess": []
  },
  "remapKeysToText": {
    "inProcess": []
  },
  "remapShortcuts": {
    "global": [
      {
        "originalKeys": "91;87",
        "newRemapKeys": "164;115"
      }
    ],
    "appSpecific": []
  }
}
'@
Set-Content -Path $ptKbmDefaultFile -Value $ptKbmDefaultContent -Encoding UTF8

$ptKbmSettingsFile = Join-Path -Path $powerToysKbmDir -ChildPath "settings.json"
$ptKbmSettingsContent = @'
{
  "name": "Keyboard Manager",
  "version": "1.0",
  "properties": {
    "activeConfiguration": {
      "value": "default"
    },
    "keyboardManager_input_remapShortcuts": {
      "value": [
        {
          "originalKeys": "91;87",
          "newRemapKeys": "164;115"
        }
      ]
    }
  }
}
'@
Set-Content -Path $ptKbmSettingsFile -Value $ptKbmSettingsContent -Encoding UTF8
Write-Host "  ✓ Configured Keyboard Manager: Win + W -> Alt + F4 (Close application Omakub style)" -ForegroundColor Green

# Launch PowerToys in background if installed
$powerToysExe = Join-Path -Path $env:ProgramFiles -ChildPath "PowerToys\PowerToys.exe"
if (Test-Path -Path $powerToysExe) {
    Start-Process -FilePath $powerToysExe -WindowStyle Hidden -ErrorAction SilentlyContinue
    Write-Host "  ✓ Started PowerToys in background." -ForegroundColor Green
}

# 7. Configure .wslconfig (RAM limit & auto-reclaim for WSL2)
Write-Host ""
Write-Host "Configuring .wslconfig (WSL 2 Performance & RAM Tuning)..." -ForegroundColor Yellow
$wslConfigFile = Join-Path -Path $env:USERPROFILE -ChildPath ".wslconfig"
if (-not (Test-Path -Path $wslConfigFile)) {
    $wslConfigContent = @'
# ==============================================================================
#  WSL 2 Configuration — Performance & RAM Management
#  Place at: C:\Users\<YourUser>\.wslconfig
# ==============================================================================
[wsl2]
# RAM limit: adjust based on your physical memory (e.g. 8GB on 16GB RAM machines)
memory=8GB

# Processors: limit to half or full physical core count
processors=4

# Swap partition size
swap=2GB

# Automatically return unused Linux memory back to Windows (prevents vmmem growth)
autoMemoryReclaim=gradual

[experimental]
sparseVhd=true
'@
    Set-Content -Path $wslConfigFile -Value $wslConfigContent -Encoding UTF8
    Write-Host "  ✓ Created .wslconfig template at $wslConfigFile" -ForegroundColor Green
    Write-Host "    (Tip: edit memory= to match ~50-75% of your RAM, then run 'wsl --shutdown' in PowerShell)" -ForegroundColor DarkGray
} else {
    Write-Host "  ✓ Existing .wslconfig detected at $wslConfigFile (skipped)." -ForegroundColor Green
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  🎉 Windows Setup Complete!                                " -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "✨ Windows & Omakub Keybindings Enabled:" -ForegroundColor Cyan
Write-Host "  • Win + Space  -> PowerToys Run (Spotlight App/File Launcher)" -ForegroundColor Yellow
Write-Host "  • Win + W      -> Close Active Application Window (Omakub style)" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Launch 'Alacritty' from your Windows Start Menu / Search." -ForegroundColor White
Write-Host "  2. It will automatically open into your WSL home directory (~)." -ForegroundColor White
Write-Host "  3. Inside WSL, simply paste this one-liner to finish setup:" -ForegroundColor White
Write-Host ""
Write-Host "     bash -c ""$(curl -fsSL https://raw.githubusercontent.com/hangodek/WSL-Environtment-Setup/main/setup.sh)""" -ForegroundColor Yellow
Write-Host ""
