<#
.SYNOPSIS
    Automated Windows Terminal Setup for WSL (Alacritty + JetBrainsMono Nerd Font)
.DESCRIPTION
    Installs Alacritty terminal emulator and JetBrainsMono Nerd Font via WinGet,
    and automatically configures Alacritty with Tokyo Night theme and WSL default shell.
.NOTES
    Run from PowerShell (no administrator privileges strictly required unless WinGet prompts).
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  🚀 Windows Terminal Setup: Alacritty + WSL Integration   " -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# 1. Check WinGet availability
Write-Host "[1/4] Checking WinGet package manager..." -ForegroundColor Yellow
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Error "WinGet is not available on this system. Please install 'App Installer' from the Microsoft Store or update Windows 10/11."
    exit 1
}
Write-Host "  ✓ WinGet is available." -ForegroundColor Green

# Helper function to install package via winget idempotently
function Install-WingetApp {
    param(
        [Parameter(Mandatory=$true)][string]$PackageId,
        [Parameter(Mandatory=$true)][string]$DisplayName,
        [string]$FallbackId = ""
    )

    Write-Host "  Checking $DisplayName ($PackageId)..." -NoNewline
    $listOutput = winget list --id $PackageId --exact 2>&1 | Out-String

    if ($listOutput -match [regex]::Escape($PackageId)) {
        Write-Host " [Already Installed]" -ForegroundColor Green
        return
    }

    if ($FallbackId) {
        $fallbackOutput = winget list --id $FallbackId --exact 2>&1 | Out-String
        if ($fallbackOutput -match [regex]::Escape($FallbackId)) {
            Write-Host " [Already Installed ($FallbackId)]" -ForegroundColor Green
            return
        }
    }

    Write-Host " [Installing...]" -ForegroundColor Yellow
    $installArgs = @("install", "--id", $PackageId, "--exact", "--silent", "--accept-package-agreements", "--accept-source-agreements")
    $process = Start-Process -FilePath "winget" -ArgumentList $installArgs -Wait -PassThru -NoNewWindow

    if ($process.ExitCode -ne 0 -and $FallbackId) {
        Write-Host "  Trying fallback ID: $FallbackId..." -ForegroundColor Yellow
        $fallbackArgs = @("install", "--id", $FallbackId, "--exact", "--silent", "--accept-package-agreements", "--accept-source-agreements")
        $process = Start-Process -FilePath "winget" -ArgumentList $fallbackArgs -Wait -PassThru -NoNewWindow
    }

    if ($process.ExitCode -eq 0) {
        Write-Host "  ✓ Successfully installed $DisplayName" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️ WinGet returned exit code $($process.ExitCode) for $DisplayName (it may require manual review or a restart)." -ForegroundColor DarkYellow
    }
}

# 2. Install Alacritty
Write-Host ""
Write-Host "[2/4] Installing Alacritty GPU-accelerated Terminal..." -ForegroundColor Yellow
Install-WingetApp -PackageId "Alacritty.Alacritty" -DisplayName "Alacritty"

# 3. Install JetBrainsMono Nerd Font
Write-Host ""
Write-Host "[3/4] Installing JetBrainsMono Nerd Font..." -ForegroundColor Yellow
Install-WingetApp -PackageId "DEVCOM.JetBrainsMonoNerdFont" -DisplayName "JetBrainsMono Nerd Font" -FallbackId "JetBrains.JetBrainsMono.NerdFont"

# 4. Configure Alacritty
Write-Host ""
Write-Host "[4/4] Configuring Alacritty for WSL & Tokyo Night Theme..." -ForegroundColor Yellow

$alacrittyConfigDir = Join-Path -Path $env:APPDATA -ChildPath "alacritty"
if (-not (Test-Path -Path $alacrittyConfigDir)) {
    New-Item -ItemType Directory -Path $alacrittyConfigDir -Force | Out-Null
}

$alacrittyConfigFile = Join-Path -Path $alacrittyConfigDir -ChildPath "alacritty.toml"

# Backup existing config if present
if (Test-Path -Path $alacrittyConfigFile) {
    $backupFile = Join-Path -Path $alacrittyConfigDir -ChildPath "alacritty.toml.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $alacrittyConfigFile -Destination $backupFile -Force
    Write-Host "  ✓ Existing configuration backed up to $(Split-Path $backupFile -Leaf)" -ForegroundColor DarkGray
}

$alacrittyConfigContent = @'
# ==============================================================================
#  Alacritty Configuration — WSL Development Environment
#  Auto-generated by WSL-Environment-Setup
# ==============================================================================

[general]
import = []

[env]
TERM = "xterm-256color"

# ------------------------------------------------------------------------------
# Terminal Shell (Directly launches WSL)
# ------------------------------------------------------------------------------
[terminal.shell]
program = "wsl.exe"
args    = ["--cd", "~"]

# ------------------------------------------------------------------------------
# Window Settings
# ------------------------------------------------------------------------------
[window]
padding         = { x = 14, y = 12 }
dynamic_padding = true
decorations     = "Full"
opacity         = 0.96
blur            = true
startup_mode    = "Maximized"
title           = "WSL (Linux)"
dynamic_title   = true

# ------------------------------------------------------------------------------
# Typography & Fonts
# ------------------------------------------------------------------------------
[font]
size = 12.5
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

# ------------------------------------------------------------------------------
# Cursor Settings
# ------------------------------------------------------------------------------
[cursor]
style          = { shape = "Beam", blinking = "On" }
blink_interval = 600

# ------------------------------------------------------------------------------
# Scrolling
# ------------------------------------------------------------------------------
[scrolling]
history    = 10000
multiplier = 3

# ------------------------------------------------------------------------------
# Color Scheme: Tokyo Night Dark (Consistent with Neovim & Zellij)
# ------------------------------------------------------------------------------
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
text   = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
background = "#283457"
text       = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

# ------------------------------------------------------------------------------
# Keybindings (Familiar copy/paste shortcuts)
# ------------------------------------------------------------------------------
[keyboard]
bindings = [
  { key = "C",     mods = "Control|Shift", action = "Copy" },
  { key = "V",     mods = "Control|Shift", action = "Paste" },
  { key = "Plus",  mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",  mods = "Control",       action = "ResetFontSize" }
]
'@

Set-Content -Path $alacrittyConfigFile -Value $alacrittyConfigContent -Encoding UTF8
Write-Host "  ✓ Wrote configuration to $alacrittyConfigFile" -ForegroundColor Green

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  🎉 Windows Terminal Setup Complete!                       " -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Launch 'Alacritty' from your Windows Start Menu / Search." -ForegroundColor White
Write-Host "  2. It will automatically open into your WSL home directory (~)." -ForegroundColor White
Write-Host "  3. Inside WSL, run './setup.sh' to finish setting up Zellij & dev tools." -ForegroundColor White
Write-Host ""
